name: fenics_arclength
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - alsa-lib=1.2.8
  - anyio=3.6.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.2.1
  - attr=2.5.1
  - attrs=23.1.0
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.4
  - beautifulsoup4=4.12.2
  - binutils_impl_linux-64=2.39
  - binutils_linux-64=2.39
  - bleach=6.0.0
  - boost-cpp=1.78.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2023.5.7
  - cairo=1.16.0
  - certifi=2023.5.7
  - cffi=1.15.1
  - charset-normalizer=3.1.0
  - cmake=3.26.4
  - comm=0.1.3
  - contourpy=1.0.7
  - cycler=0.11.0
  - dbus=1.13.6
  - debugpy=1.6.7
  - decorator=5.1.1
  - defusedxml=0.7.1
  - eigen=3.4.0
  - entrypoints=0.4
  - executing=1.2.0
  - expat=2.5.0
  - fenics=2019.1.0
  - fenics-dijitso=2019.1.0
  - fenics-dolfin=2019.1.0
  - fenics-ffc=2019.1.0
  - fenics-fiat=2019.1.0
  - fenics-libdolfin=2019.1.0
  - fenics-ufl=2019.1.0
  - fftw=3.3.10
  - flit-core=3.9.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.39.4
  - freetype=2.12.1
  - gcc_impl_linux-64=10.4.0
  - gcc_linux-64=10.4.0
  - gettext=0.21.1
  - glib=2.76.3
  - glib-tools=2.76.3
  - gmp=6.2.1
  - gmpy2=2.1.2
  - graphite2=1.3.13
  - gst-plugins-base=1.22.3
  - gstreamer=1.22.3
  - gxx_impl_linux-64=10.4.0
  - gxx_linux-64=10.4.0
  - harfbuzz=7.3.0
  - hdf5=1.12.2
  - hypre=2.25.0
  - icu=72.1
  - idna=3.4
  - importlib-metadata=6.6.0
  - importlib_metadata=6.6.0
  - importlib_resources=5.12.0
  - ipykernel=6.23.1
  - ipython=8.13.2
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.6
  - jedi=0.18.2
  - jinja2=3.1.2
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=8.2.0
  - jupyter_console=6.6.3
  - jupyter_core=5.3.0
  - jupyter_events=0.6.3
  - jupyter_server=2.6.0
  - jupyter_server_terminals=0.4.4
  - jupyterlab_pygments=0.2.2
  - jupyterlab_widgets=3.0.7
  - kernel-headers_linux-64=2.6.32
  - keyutils=1.6.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.15
  - ld_impl_linux-64=2.39
  - lerc=4.0.0
  - libaec=1.0.6
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcap=2.67
  - libcblas=3.9.0
  - libclang=16.0.4
  - libclang13=16.0.4
  - libcups=2.3.3
  - libcurl=8.1.1
  - libdeflate=1.18
  - libedit=3.1.20191231
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.5.0
  - libffi=3.4.2
  - libflac=1.4.2
  - libgcc-devel_linux-64=10.4.0
  - libgcc-ng=12.2.0
  - libgcrypt=1.10.1
  - libgfortran-ng=12.2.0
  - libgfortran5=12.2.0
  - libglib=2.76.3
  - libgomp=12.2.0
  - libgpg-error=1.46
  - libiconv=1.17
  - libjpeg-turbo=2.1.5.1
  - liblapack=3.9.0
  - libllvm16=16.0.4
  - libnghttp2=1.52.0
  - libnsl=2.0.0
  - libogg=1.3.4
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=15.3
  - libsanitizer=10.4.0
  - libsndfile=1.2.0
  - libsodium=1.0.18
  - libsqlite=3.42.0
  - libssh2=1.10.0
  - libstdcxx-devel_linux-64=10.4.0
  - libstdcxx-ng=12.2.0
  - libsystemd0=253
  - libtiff=4.5.0
  - libuuid=2.38.1
  - libuv=1.44.2
  - libvorbis=1.3.7
  - libwebp-base=1.3.0
  - libxcb=1.15
  - libxkbcommon=1.5.0
  - libxml2=2.11.4
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markupsafe=2.1.2
  - matplotlib=3.7.1
  - matplotlib-base=3.7.1
  - matplotlib-inline=0.1.6
  - metis=5.1.0
  - mistune=2.0.5
  - mpc=1.3.1
  - mpfr=4.2.0
  - mpg123=1.31.3
  - mpi=1.0
  - mpi4py=3.1.4
  - mpich=4.0.3
  - mpmath=1.3.0
  - mumps-include=5.2.1
  - mumps-mpi=5.2.1
  - munkres=1.1.4
  - mysql-common=8.0.32
  - mysql-libs=8.0.32
  - nbclassic=1.0.0
  - nbclient=0.8.0
  - nbconvert=7.4.0
  - nbconvert-core=7.4.0
  - nbconvert-pandoc=7.4.0
  - nbformat=5.8.0
  - ncurses=6.3
  - nest-asyncio=1.5.6
  - notebook=6.5.4
  - notebook-shim=0.2.3
  - nspr=4.35
  - nss=3.89
  - numpy=1.24.3
  - openjpeg=2.5.0
  - openssl=3.1.0
  - overrides=7.3.1
  - packaging=23.1
  - pandoc=2.19.2
  - pandocfilters=1.5.0
  - parmetis=4.0.3
  - parso=0.8.3
  - pcre2=10.40
  - petsc=3.17.4
  - petsc4py=3.17.4
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=9.5.0
  - pip=23.1.2
  - pixman=0.40.0
  - pkg-config=0.29.2
  - pkgconfig=1.5.5
  - pkgutil-resolve-name=1.3.10
  - platformdirs=3.5.1
  - ply=3.11
  - pooch=1.7.0
  - prometheus_client=0.17.0
  - prompt-toolkit=3.0.38
  - prompt_toolkit=3.0.38
  - psutil=5.9.5
  - pthread-stubs=0.4
  - ptscotch=6.0.9
  - ptyprocess=0.7.0
  - pulseaudio-client=16.1
  - pure_eval=0.2.2
  - pybind11=2.10.1
  - pybind11-global=2.10.1
  - pycparser=2.21
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.19.3
  - pysocks=1.7.1
  - python=3.11.3
  - python-dateutil=2.8.2
  - python-fastjsonschema=2.17.1
  - python-json-logger=2.0.7
  - python_abi=3.11
  - pyyaml=6.0
  - pyzmq=25.0.2
  - qt-main=5.15.8
  - qtconsole=5.4.3
  - qtconsole-base=5.4.3
  - qtpy=2.3.1
  - readline=8.2
  - requests=2.31.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rhash=1.4.3
  - scalapack=2.2.0
  - scipy=1.10.1
  - scotch=6.0.9
  - send2trash=1.8.2
  - setuptools=67.7.2
  - sip=6.7.9
  - six=1.16.0
  - slepc=3.17.2
  - slepc4py=3.17.2
  - sniffio=1.3.0
  - soupsieve=2.3.2.post1
  - stack_data=0.6.2
  - suitesparse=5.10.1
  - superlu=5.2.2
  - superlu_dist=7.2.0
  - sympy=1.12
  - sysroot_linux-64=2.12
  - tbb=2021.8.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.3.2
  - traitlets=5.9.0
  - typing-extensions=4.6.2
  - typing_extensions=4.6.2
  - typing_utils=0.1.0
  - tzdata=2023c
  - urllib3=2.0.2
  - wcwidth=0.2.6
  - webencodings=0.5.1
  - websocket-client=1.5.2
  - wheel=0.40.0
  - widgetsnbextension=4.0.7
  - xcb-util=0.4.0
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.0
  - xcb-util-renderutil=0.3.9
  - xcb-util-wm=0.4.1
  - xkeyboard-config=2.38
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.8.4
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xproto=7.0.31
  - xz=5.2.6
  - yaml=0.2.5
  - zeromq=4.3.4
  - zipp=3.15.0
  - zlib=1.2.13
  - zstd=1.5.2
